// [File: reactapp/src/pages/moduleB/overtime/OvertimeTicketList.js]
import React, {useState, useEffect} from 'react';
import {getFilteredOvertimeTickets} from "../../../services/moduleB/overtimeService";
import {useNavigate} from "react-router-dom";
import { getCurrentUser } from '../../../services/authService';
import { useWebSocket } from '../../../contexts/WebSocketContext';

import {
    Box, Typography, Button, Paper, TextField, InputAdornment,
    ToggleButton, ToggleButtonGroup, Table, TableBody, TableCell,
    TableContainer, TableHead, TableRow, TableSortLabel, Chip,
    colors, Grid, Card, CardContent, Stack, Tooltip, IconButton,
    TablePagination
} from '@mui/material';

import SearchIcon from '@mui/icons-material/Search';
import AddIcon from '@mui/icons-material/Add';
import VisibilityIcon from '@mui/icons-material/Visibility';
import AssignmentIcon from '@mui/icons-material/Assignment';
import {visuallyHidden} from '@mui/utils';

// --- Components ---
function StatCard({ title, value, icon, color }) {
    return (
        <Card elevation={0} sx={{ border: '1px solid #e0e0e0', borderRadius: 2, height: '100%' }}>
            <CardContent sx={{ pb: 1 }}>
                <Stack direction="row" justifyContent="space-between" alignItems="flex-start">
                    <Box>
                        <Typography color="textSecondary" variant="caption" fontWeight="bold" textTransform="uppercase">
                            {title}
                        </Typography>
                        <Typography variant="h4" fontWeight="bold" sx={{ mt: 1 }}>
                            {value}
                        </Typography>
                    </Box>
                    <Box sx={{ p: 1, bgcolor: `${color}15`, borderRadius: 2, color: color }}>
                        {icon}
                    </Box>
                </Stack>
            </CardContent>
        </Card>
    );
}

const headCells = [
    {id: 'id', label: 'Ticket ID', width: '10%'},
    {id: 'overtimeRequest.overtimeDate', label: 'Date', width: '20%'},
    {id: 'overtimeRequest.startTime', label: 'Time', width: '20%'},
    {id: 'requestId', label: 'Request Ref', width: '15%'},
    {id: 'status', label: 'Status', width: '15%'},
    {id: 'view', label: 'View', width: '10%'}
];

function EnhancedTableHead(props) {
    const {order, orderBy, onRequestSort} = props;
    const createSortHandler = (property) => (event) => {
        onRequestSort(event, property);
    };

    return (
        <TableHead>
            <TableRow sx={{"& th": {fontWeight: 'bold', backgroundColor: colors.blue[50]}}}>
                {headCells.map((headCell) => (
                    <TableCell
                        key={headCell.id}
                        align="left"
                        sortDirection={orderBy === headCell.id ? order : false}
                        width={headCell.width}
                    >
                        <TableSortLabel
                            active={orderBy === headCell.id}
                            direction={orderBy === headCell.id ? order : 'asc'}
                            onClick={createSortHandler(headCell.id)}
                            disabled={headCell.id === 'view'}
                        >
                            {headCell.label}
                            {orderBy === headCell.id ? (
                                <Box component="span" sx={visuallyHidden}>
                                    {order === 'desc' ? 'sorted descending' : 'sorted ascending'}
                                </Box>
                            ) : null}
                        </TableSortLabel>
                    </TableCell>
                ))}
            </TableRow>
        </TableHead>
    );
}

export default function OvertimeTicketList() {
    const navigate = useNavigate();
    const currentUser = getCurrentUser();
    const { subscribe, connected } = useWebSocket();

    const [tickets, setTickets] = useState([]);

    // Pagination & Sort
    const [page, setPage] = useState(0);
    const [rowsPerPage, setRowsPerPage] = useState(10);
    const [totalCount, setTotalCount] = useState(0);
    const [order, setOrder] = useState('desc');
    const [orderBy, setOrderBy] = useState('id');

    // Filters
    const [statusFilter, setStatusFilter] = useState('all');
    const [search, setSearch] = useState('');
    const [debouncedSearch, setDebouncedSearch] = useState('');

    useEffect(() => {
        const t = setTimeout(() => {
            setDebouncedSearch(search);
            setPage(0);
        }, 500);
        return () => clearTimeout(t);
    }, [search]);

    const loadData = async () => {
        if (!currentUser?.id) return;

        const apiStatus = statusFilter === 'all' ? null : statusFilter;
        const filter = {
            managerId: currentUser.id,
            status: apiStatus,
            excludeAutoGenerated: true,
        };

        if (debouncedSearch) {
            filter.requestId = debouncedSearch;
        }

        const pageable = { page, size: rowsPerPage, sort: `${orderBy},${order}` };

        try {
            const data = await getFilteredOvertimeTickets(filter, pageable);
            setTickets(data?.content || []);
            setTotalCount(data?.totalElements || 0);
        } catch (err) {
            console.error("Failed to fetch tickets", err);
        }
    };

    useEffect(() => {
        loadData();
    }, [page, rowsPerPage, statusFilter, debouncedSearch, order, orderBy, currentUser?.id]);

    useEffect(() => {
        if (!connected) return;
        const sub = subscribe('/topic/tickets', () => loadData());
        return () => { if (sub) sub.unsubscribe(); };
    }, [connected, subscribe, page, rowsPerPage, statusFilter, order, orderBy, debouncedSearch]);

    const handleSortRequest = (event, property) => {
        const isAsc = orderBy === property && order === 'asc';
        setOrder(isAsc ? 'desc' : 'asc');
        setOrderBy(property);
    };

    const handleChangePage = (event, newPage) => {
        setPage(newPage);
    };

    const handleChangeRowsPerPage = (event) => {
        setRowsPerPage(parseInt(event.target.value, 10));
        setPage(0);
    };

    const getStatusChip = (status) => {
        let color = 'default';
        if (status === 'submitted') color = 'info';
        if (status === 'approved') color = 'success';
        if (status === 'rejected') color = 'error';
        return <Chip label={status?.toUpperCase()} color={color} size="small" sx={{ fontWeight: 'bold', minWidth: 80 }} />;
    };

    const formatTime = (t) => t ? t.substring(0, 5) : '';

    return (
        <Box>
            <Grid container spacing={2} sx={{ mb: 3 }}>
                <Grid item xs={12} sm={4}>
                    <StatCard title="My Tickets" value={totalCount} icon={<AssignmentIcon />} color="#1976d2" />
                </Grid>
            </Grid>

            <Paper elevation={0} sx={{
                p: 2, mb: 2, bgcolor: 'white', border: '1px solid #eee',
                display: 'flex', gap: 2, flexWrap: 'wrap', alignItems: 'center'
            }}>
                <Typography variant="h6" sx={{ fontWeight: 'bold', mr: 2 }}>My Tickets</Typography>

                <TextField
                    size="small"
                    placeholder="Filter by Request ID..."
                    value={search}
                    onChange={(e) => setSearch(e.target.value)}
                    InputProps={{ startAdornment: <InputAdornment position="start"><SearchIcon /></InputAdornment> }}
                    sx={{ width: 300 }}
                />

                <ToggleButtonGroup
                    value={statusFilter}
                    exclusive
                    onChange={(e, v) => { if(v) { setStatusFilter(v); setPage(0); } }}
                    size="small"
                >
                    <ToggleButton value="all">All</ToggleButton>
                    <ToggleButton value="submitted" color="info">Submitted</ToggleButton>
                    <ToggleButton value="approved" color="success">Approved</ToggleButton>
                    {/*<ToggleButton value="rejected" color="error">Rejected</ToggleButton>*/}
                </ToggleButtonGroup>

                <Box flexGrow={1} />

                <Button variant="contained" startIcon={<AddIcon />} onClick={() => navigate("/overtime-ticket/create")}>
                    Create Ticket
                </Button>
            </Paper>

            <Paper elevation={0} sx={{ border: '1px solid #e0e0e0', borderRadius: 2, overflow: 'hidden' }}>
                <TableContainer>
                    <Table size="medium">
                        <EnhancedTableHead order={order} orderBy={orderBy} onRequestSort={handleSortRequest} />
                        <TableBody>
                            {tickets.length === 0 ? (
                                <TableRow><TableCell colSpan={6} align="center" sx={{ py: 4 }}>No tickets found.</TableCell></TableRow>
                            ) : (
                                tickets.map((ticket) => (
                                    <TableRow
                                        key={ticket.id}
                                        hover
                                        sx={{ cursor: 'pointer' }}
                                        onClick={() => navigate(`/overtime-ticket/${ticket.id}`)}
                                    >
                                        <TableCell><strong>#{ticket.id}</strong></TableCell>
                                        <TableCell>{ticket.overtimeDate}</TableCell>
                                        <TableCell>{formatTime(ticket.startTime)} - {formatTime(ticket.endTime)}</TableCell>
                                        <TableCell>
                                            <Chip label={`Req #${ticket.requestId}`} size="small" variant="outlined" onClick={(e) => {
                                                e.stopPropagation();
                                                navigate(`/overtime-request/${ticket.requestId}`);
                                            }} />
                                        </TableCell>
                                        <TableCell>{getStatusChip(ticket.status)}</TableCell>
                                        <TableCell>
                                            <Tooltip title="View Detail">
                                                <IconButton size="small" onClick={() => navigate(`/overtime-ticket/${ticket.id}`)}>
                                                    <VisibilityIcon fontSize="small" />
                                                </IconButton>
                                            </Tooltip>
                                        </TableCell>
                                    </TableRow>
                                ))
                            )}
                        </TableBody>
                    </Table>
                </TableContainer>

                <TablePagination
                    rowsPerPageOptions={[5, 10, 25]}
                    component="div"
                    count={totalCount}
                    rowsPerPage={rowsPerPage}
                    page={page}
                    onPageChange={handleChangePage}
                    onRowsPerPageChange={handleChangeRowsPerPage}
                    showFirstButton
                    showLastButton
                    sx={{
                        borderTop: '1px solid #e0e0e0',
                        bgcolor: '#fafafa',
                        '.MuiTablePagination-toolbar': {
                            minHeight: 52,
                            px: 2
                        },
                        '.MuiTablePagination-selectLabel, .MuiTablePagination-displayedRows': {
                            margin: 0,
                            fontWeight: 500,
                            color: 'text.secondary'
                        },
                        '.MuiTablePagination-actions': {
                            ml: 2
                        }
                    }}
                />
            </Paper>
        </Box>
    );
}