import React, {useState, useEffect} from 'react';
import {
    getFilteredOvertimeTickets
} from "../../../services/moduleB/overtimeService";

import {
    Box, Paper, TextField, InputAdornment, ToggleButton, ToggleButtonGroup,
    Table, TableBody, TableCell, TableContainer, TableHead, TableRow,
    TableSortLabel, Chip, colors, Stack, Dialog, DialogTitle,
    DialogContent, Tooltip, IconButton
} from '@mui/material';

import SearchIcon from '@mui/icons-material/Search';
import CloseIcon from '@mui/icons-material/Close';
import VisibilityIcon from '@mui/icons-material/Visibility';

import {visuallyHidden} from '@mui/utils';
import EmployeeListTable from './EmployeeList';

const headCells = [
    {id: 'id', label: 'ID', numeric: false, width: '10%'},
    {id: 'manager.fullName', label: 'Manager', numeric: false, width: '30%'},
    {id: 'employeeList', label: 'Empl #', numeric: false, width: '20%'},
    {id: 'status', label: 'Status', numeric: false, width: '20%'},
    {id: 'view', label: 'View', numeric: false, width: '10%'},
];

function EnhancedTableHead(props) {
    const {order, orderBy, onRequestSort} = props;
    const createSortHandler = (property) => (event) => {
        onRequestSort(event, property);
    };

    return (
        <TableHead>
            <TableRow sx={{"& th": {fontWeight: 'bold', backgroundColor: colors.blue[100]}}}>
                {headCells.map((headCell) => (
                    <TableCell
                        key={headCell.id}
                        sx={{ width: headCell.width }}
                        align={headCell.numeric ? 'right' : 'left'}
                        sortDirection={orderBy === headCell.id ? order : false}
                    >
                        <TableSortLabel
                            active={orderBy === headCell.id}
                            direction={orderBy === headCell.id ? order : 'asc'}
                            onClick={createSortHandler(headCell.id)}
                            disabled={headCell.id === 'view' || headCell.id === 'employeeList' || headCell.id === 'status'}
                        >
                            {headCell.label}
                            {orderBy === headCell.id ? (
                                <Box component="span" sx={visuallyHidden}>
                                    {order === 'desc' ? 'sorted descending' : 'sorted ascending'}
                                </Box>
                            ) : null}
                        </TableSortLabel>
                    </TableCell>
                ))}
            </TableRow>
        </TableHead>
    );
}

function RequestTicketList({request, refreshTrigger}) {
    const [tickets, setTickets] = useState([]);
    const [order, setOrder] = useState('desc');
    const [orderBy, setOrderBy] = useState('id');

    const [statusFilter, setStatusFilter] = useState('');
    const [managerNameSearch, setManagerNameSearch] = useState('');
    const [debouncedManagerName, setDebouncedManagerName] = useState(managerNameSearch);

    // Modals
    const [employeeModalOpen, setEmployeeModalOpen] = useState(false);
    const [selectedTicketId, setSelectedTicketId] = useState(null);

    const requestId = request?.id;

    useEffect(() => {
        const handler = setTimeout(() => {
            setDebouncedManagerName(managerNameSearch);
        }, 500);
        return () => clearTimeout(handler);
    }, [managerNameSearch]);

    useEffect(() => {
        async function loadData() {
            if (!requestId) {
                setTickets([]);
                return;
            }
            const filter = {
                requestId: requestId,
                status: statusFilter || null,
                managerName: debouncedManagerName || null,
                excludeAutoGenerated: true,
            };
            const pageable = {page: 0, size: 100, sort: `${orderBy},${order}`};
            try {
                const data = await getFilteredOvertimeTickets(filter, pageable);
                const allTickets = data?.content || [];
                const visibleTickets = allTickets.filter(ticket => ticket.status !== 'pending');
                setTickets(visibleTickets);
            } catch (err) {
                console.error("Failed to fetch tickets", err);
                setTickets([]);
            }
        }

        loadData();
    }, [requestId, statusFilter, debouncedManagerName, order, orderBy, refreshTrigger]);

    const handleStatusChange = (event, newStatus) => {
        setStatusFilter(newStatus || '');
    };

    const handleSortRequest = (event, property) => {
        const isAsc = orderBy === property && order === 'asc';
        setOrder(isAsc ? 'desc' : 'asc');
        setOrderBy(property);
    };

    const handleOpenEmployeeModal = (ticketId) => {
        setSelectedTicketId(ticketId);
        setEmployeeModalOpen(true);
    };

    const activeTicket = tickets.find(t => t.id === selectedTicketId);
    const modalEmployees = activeTicket ? activeTicket.employeeList : [];

    const getStatusChip = (status) => {
        let color;
        let label = status ? status.toUpperCase() : 'UNKNOWN';
        switch (status?.toLowerCase()) {
            case 'submitted':
                color = 'info';
                break;
            case 'approved':
                color = 'success';
                break;
            case 'rejected':
                color = 'error';
                break;
            default:
                color = 'default';
        }
        return <Chip label={label} color={color} size="small" sx={{minWidth: 90, fontWeight: 'bold'}}/>;
    };

    const getScopeText = (employeeList) => {
        if(!employeeList) return "0 Employees";
        const count = employeeList.length;
        return `${count} Employee${count !== 1 ? 's' : ''}`;
    }

    return (
        <Box sx={{ mt: 1 }}>
            <Stack direction={{xs: 'column', sm: 'row'}} spacing={2} alignItems="center" sx={{mb: 2}}>
                <TextField
                    placeholder="Search Manager..."
                    value={managerNameSearch}
                    onChange={e => setManagerNameSearch(e.target.value)}
                    variant="outlined" size="small"
                    sx={{width: 240, backgroundColor: 'white'}}
                    InputProps={{startAdornment: (<InputAdornment position="start"><SearchIcon/></InputAdornment>)}}
                />
                <Box sx={{display: 'flex', alignItems: 'center', gap: 1, flexShrink: 0}}>
                    <ToggleButtonGroup value={statusFilter} exclusive onChange={handleStatusChange} size="small" sx={{bgcolor: 'white'}}>
                        <ToggleButton value="">All</ToggleButton>
                        <ToggleButton value="submitted">Submitted</ToggleButton>
                        <ToggleButton value="approved">Approved</ToggleButton>
                        {/*<ToggleButton value="rejected">Rejected</ToggleButton>*/}
                    </ToggleButtonGroup>
                </Box>
            </Stack>

            <Paper sx={{width: '100%', mb: 0, border: '1px solid', borderColor: 'grey.300', overflow: 'hidden'}}>
                <TableContainer>
                    <Table size="small" sx={{width: '100%', tableLayout: 'fixed'}}>
                        <EnhancedTableHead order={order} orderBy={orderBy} onRequestSort={handleSortRequest}/>
                        <TableBody>
                            {tickets.length === 0 ? (
                                <TableRow><TableCell colSpan={headCells.length} align="center" sx={{py: 4}}>No tickets found.</TableCell></TableRow>
                            ) : (
                                tickets.map((ticket) => {
                                    return (
                                        <TableRow hover key={ticket.id}>
                                            <TableCell>#{ticket.id}</TableCell>
                                            <TableCell>{ticket.managerName || 'N/A'}</TableCell>
                                            <TableCell>{getScopeText(ticket.employeeList)}</TableCell>
                                            <TableCell>{getStatusChip(ticket.status)}</TableCell>
                                            <TableCell>
                                                <Tooltip title="View List">
                                                    <IconButton size="small" onClick={() => handleOpenEmployeeModal(ticket.id)}>
                                                        <VisibilityIcon fontSize="small"/>
                                                    </IconButton>
                                                </Tooltip>
                                            </TableCell>
                                        </TableRow>
                                    );
                                })
                            )}
                        </TableBody>
                    </Table>
                </TableContainer>
            </Paper>

            <Dialog open={employeeModalOpen} onClose={() => setEmployeeModalOpen(false)} maxWidth="md" fullWidth>
                <DialogTitle sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    Ticket Employees
                    <IconButton onClick={() => setEmployeeModalOpen(false)}>
                        <CloseIcon />
                    </IconButton>
                </DialogTitle>
                <DialogContent dividers sx={{ p: 0 }}>
                    <EmployeeListTable employees={modalEmployees} />
                </DialogContent>
            </Dialog>
        </Box>
    );
}

export default RequestTicketList;